name: GameLib2
description: Personal game development library, version 2
version: 0.0.1

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
#  path: ^1.4.1
  archive: ^1.0.31

dev_dependencies:
  test: ^0.12.0
